<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class TestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                "firstname" => "John",
                "lastname" => "Doe",
                "email" => "johndoe@example.test",
                "phone" => "12345678",
                "education" => "",
                "section" => "",
                "adress" => "",
                "fax" => "",
                "role" => "admin",
                "photo" => "/public/test/1.jpg",
                "password" => Hash::make("password123"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Jane",
                "lastname" => "Smith",
                "email" => "janesmith10@example.test",
                "phone" => "87654321",
                "education" => "",
                "section" => "",
                "adress" => "",
                "fax" => "",
                "role" => "admin",
                "photo" => "/public/test/2.jpg",
                "password" => Hash::make("password456"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Alice",
                "lastname" => "Johnson",
                "email" => "alicejohnson@example.test",
                "phone" => "98765432",
                "education" => "",
                "section" => "",
                "adress" => "",
                "fax" => "",
                "role" => "admin",
                "photo" => "/public/test/3.jpg",
                "password" => Hash::make("password789"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Michael",
                "lastname" => "Williams",
                "email" => "michaelwilliams@example.test",
                "phone" => "45678901",
                "education" => "",
                "section" => "",
                "adress" => "",
                "fax" => "",
                "role" => "admin",
                "photo" => "/public/test/4.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Emily",
                "lastname" => "Brown",
                "email" => "emilybrown@example.test",
                "phone" => "21098765",
                "education" => "",
                "section" => "",
                "adress" => "",
                "fax" => "",
                "role" => "admin",
                "photo" => "/public/test/5.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Daniel",
                "lastname" => "Taylor",
                "email" => "danieltaylor@example.test",
                "phone" => "54321098",
                "education" => "Master's degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/6.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Olivia",
                "lastname" => "Miller",
                "email" => "oliviamiller@example.test",
                "phone" => "10987654",
                "education" => "Doctorate degree",
                "section" => "Data science",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/7.jpg",
                "password" => Hash::make("password345"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "David",
                "lastname" => "Wilson",
                "email" => "davidwilson@example.test",
                "phone" => "43210987",
                "education" => "Bachelor's degree",
                "section" => "Cyber security",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/8.jpg",
                "password" => Hash::make("password678"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Sophia",
                "lastname" => "Jones",
                "email" => "sophiajones@example.test",
                "phone" => "76543210",
                "education" => "Master's degree",
                "section" => "Computer programming",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/9.jpg",
                "password" => Hash::make("password901"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "James",
                "lastname" => "Brown",
                "email" => "jamesbrown@example.test",
                "phone" => "87654321",
                "education" => "Doctorate degree",
                "section" => "Computer network",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/10.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Ava",
                "lastname" => "Taylor",
                "email" => "avataylor@example.test",
                "phone" => "76543210",
                "education" => "Bachelor's degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/11.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Logan",
                "lastname" => "Moore",
                "email" => "loganmoore@example.test",
                "phone" => "21098765",
                "education" => "Master's degree",
                "section" => "Data science",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/12.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Mia",
                "lastname" => "Clark",
                "email" => "miaclark@example.test",
                "phone" => "54321098",
                "education" => "Doctorate degree",
                "section" => "Cyber security",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/13.jpg",
                "password" => Hash::make("password123"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Liam",
                "lastname" => "Allen",
                "email" => "liamallen@example.test",
                "phone" => "98765432",
                "education" => "Bachelor's degree",
                "section" => "Computer programming",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/14.jpg",
                "password" => Hash::make("password456"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Isabella",
                "lastname" => "Young",
                "email" => "isabellayoung@example.test",
                "phone" => "45678901",
                "education" => "Master's degree",
                "section" => "Computer network",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/15.jpg",
                "password" => Hash::make("password789"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Benjamin",
                "lastname" => "White",
                "email" => "benjaminwhite@example.test",
                "phone" => "12345678",
                "education" => "Doctorate degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/16.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Charlotte",
                "lastname" => "King",
                "email" => "charlotteking@example.test",
                "phone" => "21098765",
                "education" => "Bachelor's degree",
                "section" => "Data science",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/17.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "William",
                "lastname" => "Young",
                "email" => "williamyoung@example.test",
                "phone" => "54321098",
                "education" => "Master's degree",
                "section" => "Cyber security",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/18.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Sophia",
                "lastname" => "Thomas",
                "email" => "sophiathomas@example.test",
                "phone" => "10987654",
                "education" => "Doctorate degree",
                "section" => "Computer programming",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/19.jpg",
                "password" => Hash::make("password345"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Alexander",
                "lastname" => "Martin",
                "email" => "alexandermartin@example.test",
                "phone" => "43210987",
                "education" => "Bachelor's degree",
                "section" => "Computer network",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/20.jpg",
                "password" => Hash::make("password678"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Amelia",
                "lastname" => "Walker",
                "email" => "ameliawalker@example.test",
                "phone" => "76543210",
                "education" => "Master's degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/21.jpg",
                "password" => Hash::make("password901"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Daniel",
                "lastname" => "Harris",
                "email" => "danielharris@example.test",
                "phone" => "87654321",
                "education" => "Doctorate degree",
                "section" => "Data science",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/22.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Olivia",
                "lastname" => "Lewis",
                "email" => "olivialewis@example.test",
                "phone" => "76543210",
                "education" => "Bachelor's degree",
                "section" => "Cyber security",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/23.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Matthew",
                "lastname" => "Clark",
                "email" => "matthewclark@example.test",
                "phone" => "21098765",
                "education" => "Master's degree",
                "section" => "Computer programming",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/24.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Abigail",
                "lastname" => "Jones",
                "email" => "abigailjones@example.test",
                "phone" => "54321098",
                "education" => "Doctorate degree",
                "section" => "Computer network",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/25.jpg",
                "password" => Hash::make("password123"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Ethan",
                "lastname" => "Brown",
                "email" => "ethanbrown@example.test",
                "phone" => "98765432",
                "education" => "Bachelor's degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/26.jpg",
                "password" => Hash::make("password456"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Harper",
                "lastname" => "Allen",
                "email" => "harperallen@example.test",
                "phone" => "45678901",
                "education" => "Master's degree",
                "section" => "Data science",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/27.jpg",
                "password" => Hash::make("password789"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Christopher",
                "lastname" => "White",
                "email" => "whitechristopher@example.test",
                "phone" => "12345678",
                "education" => "Doctorate degree",
                "section" => "Cyber security",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/28.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Elizabeth",
                "lastname" => "King",
                "email" => "elizabethking@example.test",
                "phone" => "21098765",
                "education" => "Bachelor's degree",
                "section" => "Computer programming",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/29.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Joseph",
                "lastname" => "Young",
                "email" => "josephyoung@example.test",
                "phone" => "54321098",
                "education" => "Master's degree",
                "section" => "Computer network",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/30.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Sofia",
                "lastname" => "Thomas",
                "email" => "sofiathomas@example.test",
                "phone" => "10987654",
                "education" => "Doctorate degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/31.jpg",
                "password" => Hash::make("password345"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Henry",
                "lastname" => "Martin",
                "email" => "henrymartin@example.test",
                "phone" => "43210987",
                "education" => "Bachelor's degree",
                "section" => "Data science",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/32.jpg",
                "password" => Hash::make("password678"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Ella",
                "lastname" => "Walker",
                "email" => "ellawalker@example.test",
                "phone" => "76543210",
                "education" => "Master's degree",
                "section" => "Cyber security",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/33.jpg",
                "password" => Hash::make("password901"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Andrew",
                "lastname" => "Harris",
                "email" => "andrewharris@example.test",
                "phone" => "87654321",
                "education" => "Doctorate degree",
                "section" => "Computer programming",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/34.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Victoria",
                "lastname" => "Lewis",
                "email" => "victorialewis@example.test",
                "phone" => "76543210",
                "education" => "Bachelor's degree",
                "section" => "Computer network",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/35.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "William",
                "lastname" => "Clark",
                "email" => "williamclark@example.test",
                "phone" => "21098765",
                "education" => "Master's degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/36.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Grace",
                "lastname" => "Jones",
                "email" => "gracejones@example.test",
                "phone" => "54321098",
                "education" => "Doctorate degree",
                "section" => "Data science",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/37.jpg",
                "password" => Hash::make("password123"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Michael",
                "lastname" => "Brown",
                "email" => "michaelbrown07@example.test",
                "phone" => "98765432",
                "education" => "Bachelor's degree",
                "section" => "Cyber security",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/38.jpg",
                "password" => Hash::make("password456"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Emma",
                "lastname" => "Allen",
                "email" => "emmaallen@example.test",
                "phone" => "45678901",
                "education" => "Master's degree",
                "section" => "Computer programming",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/39.jpg",
                "password" => Hash::make("password789"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Christopher",
                "lastname" => "White",
                "email" => "christopherwhite@example.test",
                "phone" => "12345678",
                "education" => "Doctorate degree",
                "section" => "Computer network",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/40.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Avery",
                "lastname" => "King",
                "email" => "averyking@example.test",
                "phone" => "21098765",
                "education" => "Bachelor's degree",
                "section" => "Artificial intelligence",
                "adress" => "",
                "fax" => "",
                "role" => "user",
                "photo" => "/public/test/41.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ], [
                "firstname" => "Jane",
                "lastname" => "Smith",
                "email" => "janesmith@example.test",
                "phone" => "87654321",
                "education" => "",
                "section" => "",
                "adress" => "456 Elm Street",
                "fax" => "98765432",
                "role" => "society",
                "photo" => "/public/test/42.jpg",
                "password" => Hash::make("password456"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "John",
                "lastname" => "Doe",
                "email" => "johndoe22@example.test",
                "phone" => "12345678",
                "education" => "",
                "section" => "",
                "adress" => "789 Oak Avenue",
                "fax" => "23456789",
                "role" => "society",
                "photo" => "/public/test/43.jpg",
                "password" => Hash::make("password123"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Emily",
                "lastname" => "Johnson",
                "email" => "emilyjohnson@example.test",
                "phone" => "98765432",
                "education" => "",
                "section" => "",
                "adress" => "321 Maple Drive",
                "fax" => "87654321",
                "role" => "society",
                "photo" => "/public/test/44.jpg",
                "password" => Hash::make("password987"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Michael",
                "lastname" => "Brown",
                "email" => "michaelbrown@example.test",
                "phone" => "56789012",
                "education" => "",
                "section" => "",
                "adress" => "654 Pine Street",
                "fax" => "54321098",
                "role" => "society",
                "photo" => "/public/test/45.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Olivia",
                "lastname" => "Davis",
                "email" => "oliviadavis@example.test",
                "phone" => "10987654",
                "education" => "",
                "section" => "",
                "adress" => "987 Cedar Avenue",
                "fax" => "43210987",
                "role" => "society",
                "photo" => "/public/test/46.jpg",
                "password" => Hash::make("password321"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Daniel",
                "lastname" => "Wilson",
                "email" => "danielwilson@example.test",
                "phone" => "54321098",
                "education" => "",
                "section" => "",
                "adress" => "876 Birch Lane",
                "fax" => "32109876",
                "role" => "society",
                "photo" => "/public/test/47.jpg",
                "password" => Hash::make("password654"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Sophia",
                "lastname" => "Garcia",
                "email" => "sophiagarcia@example.test",
                "phone" => "21098765",
                "education" => "",
                "section" => "",
                "adress" => "543 Oak Street",
                "fax" => "89012345",
                "role" => "society",
                "photo" => "/public/test/48.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "David",
                "lastname" => "Anderson",
                "email" => "davidanderson@example.test",
                "phone" => "34567890",
                "education" => "",
                "section" => "",
                "adress" => "876 Maple Lane",
                "fax" => "09876543",
                "role" => "society",
                "photo" => "/public/test/49.jpg",
                "password" => Hash::make("password234"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Emma",
                "lastname" => "Gonzalez",
                "email" => "emmagonzalez@example.test",
                "phone" => "98765432",
                "education" => "",
                "section" => "",
                "adress" => "234 Cedar Street",
                "fax" => "76543210",
                "role" => "society",
                "photo" => "/public/test/50.jpg",
                "password" => Hash::make("password678"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Noah",
                "lastname" => "Martinez",
                "email" => "noahmartinez@example.test",
                "phone" => "56789012",
                "education" => "",
                "section" => "",
                "adress" => "901 Oak Avenue",
                "fax" => "21098765",
                "role" => "society",
                "photo" => "/public/test/51.jpg",
                "password" => Hash::make("password890"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Ava",
                "lastname" => "Taylor",
                "email" => "avataylor15@example.test",
                "phone" => "10987654",
                "education" => "",
                "section" => "",
                "adress" => "567 Pine Street",
                "fax" => "87654321",
                "role" => "society",
                "photo" => "/public/test/52.jpg",
                "password" => Hash::make("password123"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "William",
                "lastname" => "Lopez",
                "email" => "williamlopez@example.test",
                "phone" => "54321098",
                "education" => "",
                "section" => "",
                "adress" => "890 Cedar Drive",
                "fax" => "43210987",
                "role" => "society",
                "photo" => "/public/test/53.jpg",
                "password" => Hash::make("password567"), 'created_at' => Carbon::now(),
            ],
            [
                "firstname" => "Mia",
                "lastname" => "Garcia",
                "email" => "miagarcia@example.test",
                "phone" => "21098765",
                "education" => "",
                "section" => "",
                "adress" => "321 Elm Street",
                "fax" => "89012345",
                "role" => "society",
                "photo" => "/public/test/54.jpg",
                "password" => Hash::make("password321"), 'created_at' => Carbon::now(),
            ]
        ];
        DB::table("users")->insert($users);
        $posts = [
            [
                'title' => 'Internship Opportunity',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. It offers an exciting opportunity for students to gain hands-on experience in the field. The internship program will cover various topics such as programming languages, software development, and project management. Apply now to kickstart your career!',
                'author' => 'janesmith@example.test',
                'education' => "Bachelor's degree",
                'section' => 'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Job Opening',
                'content' => 'This post is related to a Master\'s degree in Cyber security. We have a job opening for a cybersecurity analyst. The role requires expertise in threat detection, incident response, and vulnerability assessment. Join our team to protect against cyber threats and safeguard sensitive information.',
                'author' => 'johndoe22@example.test',
                'education' => "Master's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'AI Research Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We are seeking a highly skilled researcher to join our AI team. The role involves developing advanced algorithms, conducting experiments, and publishing research papers. If you have a strong background in AI and a passion for innovation, apply now!',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Science Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Data science. We have an exciting internship opportunity for data science enthusiasts. The program will provide hands-on experience in data analysis, machine learning, and data visualization. Join us to work on real-world projects and gain valuable skills.',
                'author' => 'michaelbrown@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Engineer Job Opening',
                'content' => 'This post is related to a Master\'s degree in Computer network. We are hiring a network engineer with expertise in designing and managing complex networks. The role involves implementing network infrastructure, troubleshooting network issues, and ensuring optimal performance. Apply now to be part of our dynamic team!',
                'author' => 'oliviadavis@example.test',
                'education' => "Master's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Web Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an internship opportunity for web developers. The program will cover front-end and back-end development, responsive design, and web security. Join our team to enhance your web development skills and contribute to exciting projects.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Analyst Position',
                'content' => 'This post is related to a Master\'s degree in Data science. We have a position open for a data analyst. The role involves analyzing large datasets, extracting insights, and generating reports. If you have strong analytical skills and a passion for data-driven decision-making, apply now!',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Security Analyst Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Cyber security. We have a job opening for a network security analyst. The role requires expertise in network security protocols, firewall management, and threat intelligence. Join our team to protect our network infrastructure and ensure data confidentiality.',
                'author' => 'davidanderson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Software Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an internship opportunity for aspiring software developers. The program will expose you to software development life cycle, agile methodologies, and collaborative coding practices. Join us to enhance your coding skills and contribute to real-world software projects.',
                'author' => 'emmagonzalez@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Database Administrator Position',
                'content' => 'This post is related to a Master\'s degree in Computer network. We are hiring a database administrator with expertise in managing and optimizing databases. The role involves database design, performance tuning, and data security. Apply now to be part of our team and ensure efficient database operations.',
                'author' => 'noahmartinez@example.test',
                'education' => "Master's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Front-End Developer Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have a job opening for a front-end developer. The role requires expertise in HTML, CSS, and JavaScript. Join our team to create user-friendly interfaces and enhance the overall user experience.',
                'author' => 'avataylor15@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Machine Learning Engineer Position',
                'content' => 'This post is related to a Master\'s degree in Artificial intelligence. We are hiring a machine learning engineer to develop and implement advanced algorithms. The role involves training models, analyzing data, and optimizing performance. Apply now to work on cutting-edge AI projects.',
                'author' => 'williamlopez@example.test',
                'education' => "Master's degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Cybersecurity Analyst Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Cyber security. We have an exciting internship opportunity for aspiring cybersecurity analysts. The program will provide hands-on experience in threat detection, incident response, and security auditing. Join us to develop practical skills in safeguarding digital assets.',
                'author' => 'miagarcia@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Engineer Position',
                'content' => 'This post is related to a Master\'s degree in Data science. We have a job opening for a data engineer. The role involves designing, building, and maintaining data pipelines. If you have a strong background in data management and data integration, apply now!',
                'author' => 'oliviadavis@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Software Quality Assurance Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an internship opportunity for individuals interested in software quality assurance. The program will cover testing methodologies, bug tracking, and test automation. Join our team to ensure high-quality software deliverables.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],  [
                'title' => 'AI Research Scientist Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We are seeking an experienced AI research scientist to lead groundbreaking projects. The role involves designing novel algorithms, conducting experiments, and collaborating with cross-functional teams. Apply now to contribute to cutting-edge AI advancements.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Database Administrator Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer network. We have an internship opportunity for aspiring database administrators. The program will provide hands-on experience in database management, query optimization, and data security. Join our team to gain practical skills in database administration.',
                'author' => 'noahmartinez@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Analyst Internship',
                'content' => 'This post is related to a Master\'s degree in Data science. We have an internship opportunity for data analysis enthusiasts. The program will cover data visualization, statistical analysis, and data-driven decision-making. Join our team to gain valuable insights from complex datasets.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Security Engineer Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Cyber security. We have a job opening for a network security engineer. The role requires expertise in securing network infrastructure, configuring firewalls, and implementing intrusion detection systems. Apply now to protect our digital assets against cyber threats.',
                'author' => 'davidanderson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Full-Stack Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an internship opportunity for aspiring full-stack developers. The program will cover front-end and back-end development, database integration, and API development. Join our team to gain comprehensive web development skills.',
                'author' => 'emmagonzalez@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],  [
                'title' => 'Cybersecurity Analyst Position',
                'content' => 'This post is related to a Master\'s degree in Cyber security. We are hiring a cybersecurity analyst to ensure the protection of our systems and data. The role involves monitoring security events, conducting risk assessments, and implementing security measures. Join our team to contribute to a secure digital environment.',
                'author' => 'johndoe22@example.test',
                'education' => "Master's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Artificial Intelligence Engineer Job Opening',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We have a job opening for an AI engineer to develop innovative AI solutions. The role involves designing neural networks, implementing algorithms, and training models. Apply now to shape the future of AI technology.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Science Researcher Position',
                'content' => 'This post is related to a Master\'s degree in Data science. We are seeking a data science researcher to contribute to our research projects. The role involves analyzing complex datasets, applying machine learning algorithms, and deriving actionable insights. Join our team to make an impact through data-driven research.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Software Development Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an internship opportunity for aspiring software developers. The program will expose you to software development best practices, coding standards, and collaborative teamwork. Join us to gain practical experience in software development.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Administrator Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Computer network. We have a job opening for a network administrator to manage our network infrastructure. The role involves configuring routers, ensuring network security, and troubleshooting network issues. Apply now to contribute to a reliable network environment.',
                'author' => 'oliviadavis@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Cybersecurity Internship',
                'content' => 'This post is related to a Master\'s degree in Cyber security. We have an exciting internship opportunity for cybersecurity enthusiasts. The program will provide hands-on experience in threat intelligence, incident response, and security audits. Join us to develop your skills and contribute to protecting digital assets.',
                'author' => 'johndoe22@example.test',
                'education' => "Master's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Artificial Intelligence Researcher Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We are looking for a dedicated AI researcher to push the boundaries of AI technology. The role involves conducting cutting-edge research, developing innovative algorithms, and publishing research papers. Apply now to advance the field of AI.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Science Consultant Job Opening',
                'content' => 'This post is related to a Master\'s degree in Data science. We have a position open for a data science consultant. The role involves working closely with clients to analyze data, provide insights, and develop data-driven strategies. Join our team to make a significant impact with your data expertise.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Software Engineering Lead Position',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We are seeking a skilled software engineering lead to oversee our development projects. The role involves leading a team, defining project roadmaps, and ensuring high-quality code delivery. Apply now to take your software engineering career to the next level.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Security Specialist Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Computer network. We have a job opening for a network security specialist. The role involves implementing security measures, conducting vulnerability assessments, and ensuring network integrity. Join our team to protect our network infrastructure from cyber threats.',
                'author' => 'oliviadavis@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Machine Learning Engineer Position',
                'content' => 'This post is related to a Master\'s degree in Data science. We have a job opening for a machine learning engineer. The role involves developing and implementing machine learning algorithms, analyzing large datasets, and creating predictive models. Join our team to contribute to cutting-edge machine learning projects.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Front-End Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an exciting internship opportunity for aspiring front-end developers. The program will focus on front-end technologies, user interface design, and responsive web development. Join us to gain practical experience and enhance your front-end skills.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Cloud Security Analyst Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Cyber security. We are hiring a cloud security analyst to ensure the security of our cloud infrastructure. The role involves implementing security measures, conducting risk assessments, and monitoring cloud environments. Apply now to protect sensitive data in the cloud.',
                'author' => 'davidanderson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Artificial Intelligence Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Artificial intelligence. We have an internship opportunity for AI enthusiasts. The program will focus on developing AI applications, implementing machine learning algorithms, and natural language processing. Join us to gain hands-on experience in the exciting field of AI.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Administrator Position',
                'content' => 'This post is related to a Master\'s degree in Computer network. We have a position open for a network administrator. The role involves managing network infrastructure, troubleshooting network issues, and implementing security protocols. Apply now to be part of our team and ensure smooth network operations.',
                'author' => 'oliviadavis@example.test',
                'education' => "Master's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Data Engineer Job Opening',
                'content' => 'This post is related to a Master\'s degree in Data science. We have a job opening for a data engineer. The role involves designing and implementing data pipelines, optimizing data storage and retrieval, and ensuring data quality. Join our team to work with large-scale data systems and contribute to data-driven decision-making.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Software Architect Position',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We are hiring a software architect to lead the design and development of software solutions. The role involves creating architectural plans, overseeing the development team, and ensuring scalability and performance. Apply now to shape the future of our software products.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Cybersecurity Consultant Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Cyber security. We have a job opening for a cybersecurity consultant. The role requires expertise in conducting security assessments, identifying vulnerabilities, and providing recommendations for risk mitigation. Join our team to help organizations enhance their cybersecurity posture.',
                'author' => 'davidanderson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Machine Learning Researcher Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We are seeking a machine learning researcher to advance the field of AI through innovative research. The role involves exploring new machine learning algorithms, analyzing complex data sets, and publishing research papers. Apply now to contribute to cutting-edge AI research.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Security Engineer Job Opening',
                'content' => 'This post is related to a Master\'s degree in Computer network. We have a job opening for a network security engineer. The role involves designing and implementing network security measures, conducting security audits, and responding to security incidents. Join our team to protect our network infrastructure from cyber threats.',
                'author' => 'oliviadavis@example.test',
                'education' => "Master's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Data Scientist Internship',
                'content' => 'This post is related to a Master\'s degree in Data science. We have an exciting internship opportunity for aspiring data scientists. The program will provide hands-on experience in data analysis, statistical modeling, and machine learning. Join us to work on real-world data projects and gain valuable insights into the field.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Senior Software Engineer Position',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We are hiring a senior software engineer to lead the development of complex software applications. The role involves architecting software solutions, mentoring junior developers, and driving innovation. Apply now to be part of our talented software engineering team.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Penetration Tester Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Cyber security. We have a job opening for a penetration tester. The role requires expertise in identifying vulnerabilities, conducting ethical hacking, and providing recommendations for security improvements. Join our team to help organizations strengthen their defenses against cyber threats.',
                'author' => 'davidanderson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Artificial Intelligence Engineer Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We are seeking an artificial intelligence engineer to develop cutting-edge AI algorithms and applications. The role involves working on natural language processing, computer vision, and machine learning projects. Apply now to shape the future of AI technology.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Administrator Job Opening',
                'content' => 'This post is related to a Master\'s degree in Computer network. We have a job opening for a network administrator. The role involves managing network infrastructure, configuring network devices, and troubleshooting network issues. Join our team to ensure the smooth operation of our network environment.',
                'author' => 'oliviadavis@example.test',
                'education' => "Master's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Cybersecurity Analyst Internship',
                'content' => 'This post is related to a Master\'s degree in Cyber security. We have an exciting internship opportunity for aspiring cybersecurity analysts. The program will provide hands-on experience in threat detection, incident response, and security assessments. Join us to develop your skills and contribute to the protection of digital assets.',
                'author' => 'johndoe22@example.test',
                'education' => "Master's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Software Development Engineer Position',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We are hiring a software development engineer to build innovative software solutions. The role involves full-stack development, software architecture design, and collaboration with cross-functional teams. Apply now to join our dynamic development team.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'AI Research Scientist Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We have an opening for an AI research scientist to advance the field of AI through cutting-edge research. The role involves developing novel algorithms, conducting experiments, and publishing research papers. Apply now to contribute to the forefront of AI innovation.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Analyst Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Data science. We have an internship opportunity for aspiring data analysts. The program will provide practical experience in data cleansing, analysis, and visualization. Join us to gain insights from complex datasets and make data-driven decisions.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Engineer Job Opening',
                'content' => 'This post is related to a Master\'s degree in Computer network. We are hiring a network engineer with expertise in designing, implementing, and managing scalable networks. The role involves optimizing network performance, troubleshooting issues, and ensuring secure connectivity. Apply now to join our network engineering team.',
                'author' => 'oliviadavis@example.test',
                'education' => "Master's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ],  [
                'title' => 'Machine Learning Engineer Position',
                'content' => 'This post is related to a Master\'s degree in Artificial intelligence. We have a job opening for a machine learning engineer to develop and deploy machine learning models. The role involves data preprocessing, model training, and performance optimization. Join our team to work on cutting-edge AI solutions.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Master's degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Front-End Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an exciting internship opportunity for aspiring front-end developers. The program will cover modern web technologies, responsive design, and user experience. Join us to enhance your front-end development skills and create engaging web applications.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Scientist Position',
                'content' => 'This post is related to a Master\'s degree in Data science. We have a position open for a data scientist with expertise in statistical analysis and machine learning. The role involves deriving insights from complex datasets, developing predictive models, and communicating findings to stakeholders. Apply now to join our data science team.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Security Engineer Job Opening',
                'content' => 'This post is related to a Bachelor\'s degree in Computer network. We have a job opening for a network security engineer. The role requires expertise in network security protocols, vulnerability assessments, and security incident response. Join our team to protect our network infrastructure from cyber threats.',
                'author' => 'oliviadavis@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Web Application Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an internship opportunity for web application developers. The program will cover back-end development, API integration, and database management. Join our team to gain practical experience in building scalable web applications.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Cybersecurity Analyst Position',
                'content' => 'This post is related to a Master\'s degree in Cyber security. We have a job opening for a cybersecurity analyst to assess and mitigate security risks. The role involves conducting security audits, implementing security measures, and monitoring systems for potential threats. Join our team to protect our organization from cyber attacks.',
                'author' => 'johndoe22@example.test',
                'education' => "Master's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Artificial Intelligence Researcher Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We are seeking a skilled researcher to contribute to our AI projects. The role involves developing innovative algorithms, conducting experiments, and pushing the boundaries of AI technology. Apply now to be part of our cutting-edge research team.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Data Engineer Position',
                'content' => 'This post is related to a Bachelor\'s degree in Data science. We have a position open for a data engineer to design and maintain our data infrastructure. The role involves data integration, database management, and data pipeline development. Join our team to build robust data solutions.',
                'author' => 'sophiagarcia@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Administrator Job Opening',
                'content' => 'This post is related to a Master\'s degree in Computer network. We have a job opening for a network administrator to ensure the smooth operation of our network infrastructure. The role involves network monitoring, troubleshooting network issues, and implementing network upgrades. Apply now to join our dynamic IT team.',
                'author' => 'oliviadavis@example.test',
                'education' => "Master's degree",
                'section' =>
                'Computer network',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Full Stack Web Developer Internship',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have an exciting internship opportunity for full stack web developers. The program will cover both front-end and back-end development, database management, and version control. Join our team to gain hands-on experience in building complete web applications.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ], [
                'title' => 'Software Development Engineer Position',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have a job opening for a software development engineer to design and develop robust software solutions. The role involves coding, debugging, and collaborating with cross-functional teams. Join our organization to contribute to innovative software products.',
                'author' => 'emmagonzalez@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Database Analyst Position',
                'content' => 'This post is related to a Master\'s degree in Data science. We are hiring a database analyst to analyze and optimize our data infrastructure. The role involves data modeling, performance tuning, and data quality assurance. Apply now to join our team and drive data-driven decision-making.',
                'author' => 'noahmartinez@example.test',
                'education' => "Master's degree",
                'section' =>
                'Data science',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Network Security Engineer Position',
                'content' => 'This post is related to a Bachelor\'s degree in Cyber security. We have a position open for a network security engineer to safeguard our network assets. The role involves implementing security measures, conducting vulnerability assessments, and responding to security incidents. Join our team to protect our organization from cyber threats.',
                'author' => 'davidanderson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Cyber security',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Machine Learning Researcher Position',
                'content' => 'This post is related to a Doctorate degree in Artificial intelligence. We are seeking a talented researcher to advance the field of machine learning. The role involves developing novel algorithms, analyzing large datasets, and publishing research papers. Apply now to contribute to groundbreaking AI research.',
                'author' => 'emilyjohnson@example.test',
                'education' => "Doctorate degree",
                'section' =>
                'Artificial intelligence',
                'created_at' => Carbon::now(),
            ],
            [
                'title' => 'Web Application Developer Position',
                'content' => 'This post is related to a Bachelor\'s degree in Computer programming. We have a job opening for a web application developer to create user-friendly web interfaces. The role involves front-end development, responsive design, and optimizing website performance. Join our team to craft engaging web experiences.',
                'author' => 'danielwilson@example.test',
                'education' => "Bachelor's degree",
                'section' =>
                'Computer programming',
                'created_at' => Carbon::now(),
            ],
        ];
        DB::table("posts")->insert($posts);
        $postualtions = [
             [
                "status" => "rejected",
                "email" => "whitechristopher@example.test",
                "adress" => "654 Maple Avenue",
                "fax" => "95848675",
                'created_at' => Carbon::now(),
            ], [
                "status" => "approved",
                "email" => "janesmith@example.test",
                "adress" => "456 Elm Street",
                "fax" => "98765432",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "rejected",
                "email" => "emilybrown@example.test",
                "adress" => "987 Cedar Lane",
                "fax" => "90852154",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "johndoe22@example.test",
                "adress" => "789 Oak Avenue",
                "fax" => "23456789",
                'created_at' => Carbon::now(),
            ],
            [
                "email" => "emilyjohnson@example.test",
                "status" => "approved",
                "adress" => "321 Maple Drive",
                "fax" => "87654321",
                'created_at' => Carbon::now(),
            ],
            [
                "email" => "michaelbrown@example.test",
                "status" => "approved",
                "adress" => "654 Pine Street",
                "fax" => "54321098",
                'created_at' => Carbon::now(),
            ],
            [
                "email" => "oliviadavis@example.test",
                "status" =>
                "approved",
                "adress" => "987 Cedar Avenue",
                "fax" => "43210987",
                'created_at' => Carbon::now(),
            ], [
                "status" => "rejected",
                "email" => "williamclark@example.test",
                "adress" => "456 Elm Avenue",
                "fax" => "98982891",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "danielwilson@example.test",
                "adress" => "876 Birch Lane",
                "fax" => "32109876",
                'created_at' => Carbon::now(),
            ],  [
                "status" => "rejected",
                "email" => "averyking@example.test",
                "adress" => "321 Pine Street",
                "fax" => "85324591",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "sophiagarcia@example.test",
                "adress" => "543 Oak Street",
                "fax" => "89012345",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "davidanderson@example.test",
                "adress" => "876 Maple Lane",
                "fax" => "09876543",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "emmagonzalez@example.test",
                "adress" => "234 Cedar Street",
                "fax" => "76543210",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "noahmartinez@example.test",
                "adress" => "901 Oak Avenue",
                "fax" => "21098765",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "avataylor15@example.test",
                "adress" => "567 Pine Street",
                "fax" => "87654321",
                'created_at' => Carbon::now(),
            ], [
                "status" => "rejected",
                "email" => "michaelbrown07@example.test",
                "adress" => "123 Main Street",
                "fax" => "63827195",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "williamlopez@example.test",
                "adress" => "890 Cedar Drive",
                "fax" => "43210987",
                'created_at' => Carbon::now(),
            ], [
                "status" => "rejected",
                "email" => "christopherwhite@example.test",
                "adress" => "789 Oak Lane",
                "fax" => "65218657",
                'created_at' => Carbon::now(),
            ],
            [
                "status" => "approved",
                "email" => "miagarcia@example.test",
                "adress" => "321 Elm Street",
                "fax" => "89012345",
                'created_at' => Carbon::now(),
            ]
        ];
        DB::table("postulations")->insert($postualtions);
    }
}
